// createSlice defines Redux state + reducers and auto-generates action creators.
import { createSlice } from "@reduxjs/toolkit";

// Read any previously saved cart from localStorage so the cart persists across page reloads.
// localStorage stores strings, so we parse the JSON back into an array; fallback to [] when empty.
const savedCart = JSON.parse(localStorage.getItem("cart")) || [];

// Define a Redux "slice" for cart state.
// A slice bundles the initial state, reducers (state updates), and action creators in one place.
const cartSlice = createSlice({
  // Slice name is used to namespace generated action types (e.g., "cart/addToCart").
  name: "cart",

  // Initial state is seeded from localStorage so users see the same cart after refresh.
  initialState: {
    cartItems: savedCart
  },

  reducers: {
    // addToCart receives the product as action.payload and appends it to cartItems.
    // Redux Toolkit uses Immer under the hood, so mutating state here is safe.
    // We also persist the updated cart to localStorage to keep the cart in sync.
    addToCart: (state, action) => {
      state.cartItems.push(action.payload);
      localStorage.setItem("cart", JSON.stringify(state.cartItems));
    },

    // removeFromCart receives a product id as action.payload and removes matching items.
    // Filter returns a new array without the removed item(s), then we persist it.
    removeFromCart: (state, action) => {
      state.cartItems = state.cartItems.filter(
        item => item.id !== action.payload
      );

      localStorage.setItem("cart", JSON.stringify(state.cartItems));
    }
  }
});

// Export action creators generated by createSlice for use in components.
export const { addToCart, removeFromCart } = cartSlice.actions;
// Export the reducer to be added to the Redux store.
export default cartSlice.reducer;
